import { FEATURE_FLAGS, getFeatureFlags } from '../lib/constants'

interface FeatureFlag {
  key: keyof typeof FEATURE_FLAGS
  label: string
  description: string
  category: string
  enabled: boolean
}

/**
 * Auto-generate feature flag metadata from flag keys
 * This makes the system extensible - new flags are automatically detected
 */
function autoGenerateFlagMetadata(key: keyof typeof FEATURE_FLAGS): FeatureFlag {
  // Convert flag key to human-readable format
  const label = key
    .replace(/_/g, ' ')
    .replace(/\b\w/g, l => l.toUpperCase())
    .replace('Enabled', '')
    .trim()
  
  // Auto-generate category based on key patterns
  let category = 'General'
  let description = `Enable ${label.toLowerCase()} functionality`
  
  if (key.includes('AUTH')) {
    category = 'Authentication'
    description = 'Enable user authentication and account management features'
  } else if (key.includes('TTS') || key.includes('VOICE') || key.includes('SPEECH')) {
    category = 'Voice'
    description = 'Enable text-to-speech and voice-related features'
  } else if (key.includes('LLM') || key.includes('MODEL') || key.includes('AI')) {
    category = 'AI Models'
    description = 'Enable AI model provider integrations'
 } else if (key.includes('RATE') || key.includes('LIMIT')) {
    category = 'Rate Limiting'
    description = 'Control usage limits and rate limiting functionality'
  } else if (key.includes('BROWSER') || key.includes('WEB')) {
    category = 'Browser'
    description = 'Enable browser-native features and APIs'
  } else if (key.includes('CLOUD') || key.includes('API')) {
    category = 'Cloud Services'
    description = 'Enable cloud-based service integrations'
  } else if (key.includes('LOCAL') || key.includes('OFFLINE')) {
    category = 'Local Features'
    description = 'Enable offline and local processing features'
  }
  
  // Override with specific descriptions for known flags
  const specificDescriptions: Record<string, string> = {
    'AUTH_ENABLED': 'Enable user authentication, login/logout, and account management',
    'TTS_ENABLED': 'Enable AI response voice readout using text-to-speech',
    'OLLAMA_ENABLED': 'Enable local Ollama model integration for offline AI',
    'CLOUD_LLM_ENABLED': 'Enable cloud-based LLM providers (OpenAI, etc.)',
    'BROWSER_LLM_ENABLED': 'Enable browser-native AI models (Gemini Nano, Phi)',
    'RATE_LIMITING_ENABLED': 'Enable usage limits for anonymous users'
  }
  
  if (specificDescriptions[key]) {
    description = specificDescriptions[key]
  }
  
  return {
    key,
    label,
    description,
    category,
    enabled: getFeatureFlags()[key]
  }
}

/**
 * Get all feature flags with auto-generated metadata
 * This function automatically detects new flags and generates UI metadata
 */
export function getAutoGeneratedFeatureFlags(): FeatureFlag[] {
  const currentFlags = getFeatureFlags()
  
  return Object.keys(currentFlags).map(key => 
    autoGenerateFlagMetadata(key as keyof typeof FEATURE_FLAGS)
  )
}

/**
 * Categorize flags for better UI organization
 */
export function getCategorizedFlags(flags: FeatureFlag[]): Record<string, FeatureFlag[]> {
  return flags.reduce((acc, flag) => {
    if (!acc[flag.category]) {
      acc[flag.category] = []
    }
    acc[flag.category].push(flag)
    return acc
  }, {} as Record<string, FeatureFlag[]>)
}

/**
 * Enhanced feature flag system that supports:
 * - Automatic detection of new flags
 * - Auto-generated UI metadata
 * - Dynamic categorization
 * - Custom flag descriptions
 */
export const FLAG_SYSTEM = {
  getAllFlags: getAutoGeneratedFeatureFlags,
  getCategorizedFlags,
  
  // Allow custom flag metadata to override auto-generation
  setCustomMetadata(flagKey: keyof typeof FEATURE_FLAGS, metadata: Partial<FeatureFlag>) {
    // This would be stored in localStorage or a config file
    const customKey = `flag-metadata-${flagKey}`
    localStorage.setItem(customKey, JSON.stringify(metadata))
  },
  
  // Get flag with custom metadata applied
  getFlag(flagKey: keyof typeof FEATURE_FLAGS): FeatureFlag {
    const autoFlag = autoGenerateFlagMetadata(flagKey)
    
    // Apply any custom metadata
    try {
      const customKey = `flag-metadata-${flagKey}`
      const customData = localStorage.getItem(customKey)
      if (customData) {
        const custom = JSON.parse(customData)
        return { ...autoFlag, ...custom }
      }
    } catch (error) {
      console.warn('Error loading custom flag metadata:', error)
    }
    
    return autoFlag
  }
}