import { AgentRuntime } from "./agent-runtime";
import { LLMMessage } from "./types";

/**
 * MemoryReflector
 * 
 * A specialized, lightweight agent that consumes conversation history
 * in the background and extracts entities/facts to save to long-term memory.
 * 
 * It runs silently and does not block the main UI.
 */
export class MemoryReflector {
    private static instance: MemoryReflector;
    private isAnalyzing = false;

    private constructor() { }

    static getInstance(): MemoryReflector {
        if (!MemoryReflector.instance) {
            MemoryReflector.instance = new MemoryReflector();
        }
        return MemoryReflector.instance;
    }

    /**
     * Fire-and-forget analysis of recent conversation history.
     */
    async analyze(recentHistory: LLMMessage[], settings: any) {
        if (this.isAnalyzing) {
            console.log('[MemoryReflector] Skipping analysis - already busy');
            return;
        }

        // Only analyze if there's substantial new content
        if (recentHistory.length < 2) return;

        this.isAnalyzing = true;
        console.log('[MemoryReflector] Starting background analysis...');

        try {
            // Take the last 4 messages to keep context small but relevant
            const contextWindow = recentHistory.slice(-4);

            const reflectorAgent = new AgentRuntime({
                settings,
                isSubAgent: true,
                requireConfirmation: false,
                // We don't listen to messages, just results
                onMessage: (msg: LLMMessage) => {
                    // console.log('[MemoryReflector] Internal thought:', msg.content);
                }
            });

            // Specific prompt for the reflector
            const prompt = `
SYSTEM_TASK: BACKGROUND_MEMORY_EXTRACTION

You are the "Memory Reflector". Your ONLY job is to analyze the conversation below and save permanent user preferences, project facts, workflows, or **implicit** working patterns.

**DEDUPLICATION PROTOCOL (CRITICAL)**:
1. FIRST: Use \`memory_search\` to check if the concept/preference/entity ALREADY exists.
2. IF EXISTS: Use \`memory_update_entity\` with the existing entity's ID to APPEND a new observation.
3. IF NOT EXISTS: Use \`memory_create_entity\` to create a new entity.

CONVERSATION:
${contextWindow.map(m => `${m.role.toUpperCase()}: ${typeof m.content === 'string' ? m.content : '[Multimedia]'}`).join('\n')}

WHAT TO EXTRACT:
1. **Explicit Preferences**: Statements like "I like dark mode", "Use Python".
2. **Selections & Favorites**: Specific choices made by the user (e.g., "I prefer the Casio F-91W", "Add X to cart").
   - Save as Entity Type: "user_preference" or "product_choice".
3. **Workflows & SOPs**: Repeated processes or rules (e.g., "Always run tests before commit").
   - Save as Entity Type: "workflow" or "sop".
4. **Implicit Intent**: User's implicit intent (e.g., "Create a Next.js app" -> Save entity "Next.js" with type "technology_preference").
5. **Project Facts**: Facts about the current project (e.g., goals, stack, deadlines).

ANTI-BLOAT RULES (CRITICAL):
- **DO NOT** save ephemeral context (e.g., "User asked to fix a typo", "User said hello").
- **DO NOT** save one-off instructions as permanent preferences unless clearly stated.
- **DO NOT** create duplicate entities. ALWAYS search first and update if exists.
- Only save **high-value, permanent** information useful in a *future* session.

GOAL: Extract High-Value Implicit & Explicit Memories. Avoid Duplicates & Bloat. Then Stop.
            `;

            console.log('[MemoryReflector] Sending prompt to reflector agent...');
            const response = await reflectorAgent.chat(prompt);
            console.log('[MemoryReflector] Analysis complete. Result:', response.content);

            // Log tool calls if any
            if (response.tool_calls && response.tool_calls.length > 0) {
                console.log(`[MemoryReflector] LLM generated ${response.tool_calls.length} tool calls.`);
            } else {
                console.log('[MemoryReflector] No tool calls generated by LLM.');
            }

        } catch (error) {
            console.warn('[MemoryReflector] Background analysis failed (non-fatal):', error);
        } finally {
            this.isAnalyzing = false;
        }
    }
}
